name = "learning-os"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "learning-os"
database_id = "b34bec87-456e-4564-935d-445d6cb0fc7e"
migrations_dir = "migrations"

[vars]
GITHUB_REPO = "Coderopp/personal-learning-os"
GITHUB_BRANCH = "main"
LLM_LARGE = "openai/gpt-oss-120b"
LLM_FAST = "openai/gpt-oss-20b"
