// Bundles prompts/*.md into server/prompts.gen.ts so the gateway always runs the versioned prompts.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const dir = new URL('../prompts/', import.meta.url)
const entries = readdirSync(dir)
  .filter(f => f.endsWith('.md'))
  .sort()
  .map(f => `  ${JSON.stringify(f.replace(/\.md$/, ''))}: ${JSON.stringify(readFileSync(new URL(f, dir), 'utf8'))},`)

writeFileSync(
  new URL('../server/prompts.gen.ts', import.meta.url),
  `// Generated by scripts/build-prompts.mjs from /prompts. Do not edit.\nexport const PROMPTS = {\n${entries.join('\n')}\n} as const\n\nexport type PromptName = Exclude<keyof typeof PROMPTS, '_shared'>\n`,
)
console.log(`bundled ${entries.length} prompts`)
